//! Native version + update-available check.
//!
//! NATIVE-ONLY. The web build is always current by construction, so an
//! indicator there would be meaningless.
//!
//! Spec: `docs/superpowers/specs/2026-07-29-native-version-update-indicator-design.md`
//!
//! ## Why this exists
//!
//! A native build gave the player no way to tell what they were running. On
//! 2026-07-29 a `/bug` sent "from the native AppImage" never arrived — the
//! installed build turned out to be from 9 June, a month older than the release
//! that added the native mailbox, and nothing in the running game said so.
//!
//! ## Shape
//!
//! [`spawn_check`] does the network call on a worker thread and reports exactly
//! one [`UpdateState`] back through an `mpsc` channel — the same off-thread
//! pattern as `native_file_dialog.rs` and `native_signin.rs`, for the same
//! reason: a blocking request on the render thread stalls the frame loop.
//!
//! ## Privacy
//!
//! The request is a plain GET of a static document: no identifiers, no cookies,
//! no query string, no body, no telemetry. That keeps it unambiguously a version
//! check rather than data collection. `AXENSTAX_NO_UPDATE_CHECK=1` skips it
//! entirely, so a self-hoster's build never touches AxeNStax infrastructure.

use std::cmp::Ordering;
use std::sync::Mutex;
use std::sync::atomic::{AtomicBool, Ordering as AtomicOrdering};

/// Where the clickable "(vX available)" fragment sends the player.
pub const DOWNLOAD_PAGE: &str = "https://docs.axenstax.org/download";

/// Static version manifest, generated by the docs site from the SAME
/// `_discover_installers()` call that renders the download page — so the
/// advertised version cannot drift from the files actually downloadable.
const LATEST_URL: &str = "https://docs.axenstax.org/download/latest.json";

/// Set to any non-empty value to skip the check entirely (no network call).
const OPT_OUT_ENV: &str = "AXENSTAX_NO_UPDATE_CHECK";

/// What the lobby header should say about this build.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum UpdateState {
    /// Opted out, still in flight, or the check failed. Show the bare version
    /// with no suffix — never an error, never a nag.
    Unknown,
    /// Running the newest published build.
    Current,
    /// A newer build exists. Carries its version string, plus enough to
    /// fetch and verify it in place when this build IS the AppImage running
    /// it (`self_update`) — `None` on a manifest that predates the
    /// sha256/url fields, or that has a null/malformed one.
    Available {
        version: String,
        appimage: Option<AppImageRef>,
    },
    /// This build is NEWER than anything published — a dev or CI build. Worth
    /// distinguishing from `Current`: it usually means someone is running a
    /// local build, and silently calling that "latest" would be a lie.
    Ahead,
}

/// What `self_update` needs to fetch and verify the newest Linux AppImage,
/// pulled from `latest.json`'s `linux_appimage` / `linux_appimage_url` /
/// `linux_appimage_sha256` fields. Present only when all three are non-null
/// strings and the sha256 looks like a real sha256 (64 lowercase hex chars —
/// lowercased on parse, so an uppercase manifest value still matches).
///
/// TRUST (audit 2026-09-27): an `AppImageRef` handed to `self_update` always
/// comes from the SIGNED kind-30063 release event — `url`, `sha256` and
/// `filename` are all signed-event values. The unsigned HTTP manifest can only
/// add a URL to `mirrors`, and `self_update` accepts a mirror's bytes only if
/// they hash to the signed `sha256`. See [`decide`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AppImageRef {
    pub filename: String,
    pub url: String,
    pub sha256: String,
    /// Extra download locations (the HTTP manifest's URL), tried after `url`.
    /// Their bytes are held to the same signed `sha256`.
    pub mirrors: Vec<String>,
}

/// A safe AppImage filename: a bare basename of `[A-Za-z0-9._-]+`, ending in
/// `.AppImage`. `self_update` builds its `.part` path from this name, so
/// anything with a separator or traversal would write outside the AppImage's
/// own directory.
pub(crate) fn is_valid_appimage_filename(name: &str) -> bool {
    name.len() > ".AppImage".len()
        && name.ends_with(".AppImage")
        && name
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || matches!(c, '.' | '_' | '-'))
}

/// The `version` + optional [`AppImageRef`] pulled out of one update source
/// (`latest.json` today, a kind-30063 Nostr release event too — see
/// `nostr_release::parse_release_event`). Kept separate from `UpdateState`
/// because `compare_versions` only wants the version string; the AppImage
/// details ride along unchanged into whichever `UpdateState` variant the
/// comparison produces.
///
/// `pub(crate)` (not private) so `nostr_release` — a sibling module, not a
/// submodule — can build one directly rather than round-tripping through a
/// constructor function.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct Latest {
    pub(crate) version: String,
    pub(crate) appimage: Option<AppImageRef>,
}

/// The version this binary was compiled as.
pub fn current_version() -> &'static str {
    env!("CARGO_PKG_VERSION")
}

/// The answer, once known. Process-global because "what version is published"
/// is a fact about the process, not about any one menu instance.
///
/// A global rather than an `mpsc::Receiver` threaded through `MenuState`
/// deliberately: `MenuState::new()` runs again every time the player returns to
/// the lobby, and a per-instance receiver would re-fire the request each time.
/// Mirrors the existing `touch_input::TOUCH_DEVICE` precedent.
static RESULT: Mutex<UpdateState> = Mutex::new(UpdateState::Unknown);

/// Guards against spawning the worker more than once per process.
static STARTED: AtomicBool = AtomicBool::new(false);

/// What to show right now. Cheap enough to call every frame; before the worker
/// finishes (or when opted out) this is [`UpdateState::Unknown`], which renders
/// as a bare version with no suffix.
pub fn state() -> UpdateState {
    RESULT
        .lock()
        .map(|s| s.clone())
        .unwrap_or(UpdateState::Unknown)
}

/// Kick off the check once per process. Safe to call repeatedly; only the first
/// call does anything.
///
/// `relays` is the player's "Your relays" list (`GraphicsSettings.online_relays`),
/// passed in by the caller so the worker never re-reads settings.json; the
/// signed release feed is read from those relays only.
///
/// Returns immediately — the request runs on a worker thread, because a blocking
/// call on the render thread stalls the frame loop.
pub fn start_once(relays: Vec<String>) {
    if STARTED.swap(true, AtomicOrdering::SeqCst) {
        return;
    }
    if std::env::var(OPT_OUT_ENV).is_ok_and(|v| !v.is_empty()) {
        log::info!("update check disabled by {OPT_OUT_ENV}");
        return;
    }
    std::thread::spawn(move || {
        // Two independent sources, queried one after the other on this same
        // worker thread (still off the render thread either way — see the
        // module doc). `docs.axenstax.org/download/latest.json` is a single
        // web host reached over a publish pipeline that has gone dark before
        // (2026-09: an unresponsive sshd left it three versions stale for
        // days); `nostr_release` needs no web server at all. They are NOT
        // equals: the signed release event is the only authority for what
        // gets installed, and the HTTP manifest is a mirror / notify-only
        // hint — see `decide`. A source that failed is `None`, i.e. absent,
        // never "this one says you're current".
        let http = fetch_latest_version();
        let nostr = crate::nostr_release::fetch_latest(&relays);
        let state = decide(current_version(), http, nostr);
        log::debug!("update check: {state:?}");
        if let Ok(mut slot) = RESULT.lock() {
            *slot = state;
        }
    });
}

/// Combine the two update sources into what the lobby shows (audit 2026-09-27:
/// "the signed Nostr release channel can be bypassed").
///
/// The SIGNED kind-30063 event (`signed`, already verified against the pinned
/// release key by `nostr_release`) is the only authority for the version, the
/// download URL and the sha256. The unsigned HTTP manifest (`http`) is at most:
/// - a mirror hint — its URL is appended to the signed ref's `mirrors`, where
///   `self_update` accepts it only if the bytes hash to the SIGNED sha256; or
/// - with no signed event at all, a notify-only "update available" with NO
///   AppImage ref, so it can never trigger an install.
///
/// A compromised docs host can therefore at worst show a bogus "vX available"
/// label pointing at the download page; it can never choose the bytes.
pub(crate) fn decide(current: &str, http: Option<Latest>, signed: Option<Latest>) -> UpdateState {
    match (signed, http) {
        (Some(mut s), http) => {
            if let Some(r) = s.appimage.as_mut()
                && let Some(h) = http.and_then(|h| h.appimage)
                && h.url != r.url
                // Unsigned source: https only, so it can't aim the client at a
                // plain-http LAN address (review S7).
                && h.url.starts_with("https://")
            {
                r.mirrors.push(h.url);
            }
            compare_versions(current, s)
        }
        (None, Some(h)) => compare_versions(current, Latest { version: h.version, appimage: None }),
        (None, None) => UpdateState::Unknown,
    }
}

/// Fetch the published version (+ AppImage reference, when present). `None`
/// on ANY failure — offline, DNS, timeout, non-200, malformed JSON, missing
/// field. Every one of those means the same thing to the player: show the
/// bare version and say nothing.
fn fetch_latest_version() -> Option<Latest> {
    // redirects(0) mirrors `mc_import::http_get_text`: a redirect surfaces as a
    // non-200 and is treated as failure rather than followed.
    let agent = ureq::AgentBuilder::new()
        .timeout(std::time::Duration::from_secs(5))
        .redirects(0)
        .build();
    let body = agent.get(LATEST_URL).call().ok()?.into_string().ok()?;
    parse_latest(&body)
}

/// The client half of the `/download/latest.json` contract: pull `version`
/// (and, when present, the AppImage sha256/url) out of the document the docs
/// site emits. Split from the network call so the contract is unit-testable —
/// the design doc requires a test that the JSON keys the server writes are the
/// keys the client reads, and nothing else enforces that. `None` for
/// malformed JSON, a missing/`null`/non-string `version` (the site emits
/// `null` when no installer has been published yet), or an empty string.
fn parse_latest(body: &str) -> Option<Latest> {
    let json: serde_json::Value = serde_json::from_str(body).ok()?;
    let v = json.get("version")?.as_str()?;
    if v.is_empty() {
        return None;
    }
    Some(Latest {
        version: v.to_string(),
        appimage: parse_appimage_ref(&json),
    })
}

/// Pull `linux_appimage` / `linux_appimage_url` / `linux_appimage_sha256` out
/// of the manifest. `None` unless all three are present, non-null strings AND
/// the sha256 is a plausible sha256 (64 hex chars) — an older 4-key manifest,
/// a manifest with no Linux build yet (all three null), or a malformed sha
/// must never be handed to `self_update`, which trusts this value completely.
fn parse_appimage_ref(json: &serde_json::Value) -> Option<AppImageRef> {
    let filename = json.get("linux_appimage")?.as_str()?;
    let url = json.get("linux_appimage_url")?.as_str()?;
    let sha256 = json.get("linux_appimage_sha256")?.as_str()?;
    if !is_valid_appimage_filename(filename) || url.is_empty() {
        return None;
    }
    Some(AppImageRef {
        filename: filename.to_string(),
        url: url.to_string(),
        sha256: normalize_sha256(sha256)?,
        mirrors: Vec::new(),
    })
}

/// Validate + lowercase a sha256 hex string (64 lowercase hex chars after
/// normalising). Shared by both update sources — `self_update` trusts this
/// value completely, so a malformed one (wrong length, non-hex) must never
/// reach it from either `latest.json` or a Nostr release event.
pub(crate) fn normalize_sha256(sha256: &str) -> Option<String> {
    if sha256.len() != 64 || !sha256.chars().all(|c| c.is_ascii_hexdigit()) {
        return None;
    }
    Some(sha256.to_ascii_lowercase())
}

/// Compare two dotted numeric versions. `latest` carries the AppImage
/// reference (if any) through unchanged into the `Available` variant.
///
/// The version comparison is pure, and the only place where a real bug can
/// hide — hence the unit tests below. Anything unparseable on either side
/// yields [`UpdateState::Unknown`] rather than a guess: showing nothing beats
/// showing something wrong.
fn compare_versions(current: &str, latest: Latest) -> UpdateState {
    let (Some(c), Some(l)) = (parse_version(current), parse_version(&latest.version)) else {
        return UpdateState::Unknown;
    };
    match c.cmp(&l) {
        Ordering::Less => UpdateState::Available {
            version: latest.version,
            appimage: latest.appimage,
        },
        Ordering::Equal => UpdateState::Current,
        Ordering::Greater => UpdateState::Ahead,
    }
}

/// Parse `"0.2.16"` into `[0, 2, 16, 0]`.
///
/// Padded to a fixed width so `"0.2"` and `"0.2.0"` compare equal, and so a
/// plain `Vec` ordering is a correct version ordering. Rejects empty strings,
/// non-numeric segments, and anything longer than four segments.
fn parse_version(v: &str) -> Option<[u32; 4]> {
    let v = v.trim().trim_start_matches('v');
    if v.is_empty() {
        return None;
    }
    let mut out = [0u32; 4];
    for (n, seg) in v.split('.').enumerate() {
        // Guards both "more segments than we hold" and an empty segment from a
        // doubled dot ("0.2..16"), which `parse` would otherwise reject anyway
        // but less clearly.
        if n >= out.len() || seg.is_empty() {
            return None;
        }
        out[n] = seg.parse::<u32>().ok()?;
    }
    Some(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Test-only shorthand for a `Latest` with no AppImage reference — most
    /// version-comparison tests don't care about it.
    fn bare(v: &str) -> Latest {
        Latest { version: v.to_string(), appimage: None }
    }

    fn available(v: &str) -> UpdateState {
        UpdateState::Available { version: v.to_string(), appimage: None }
    }

    const REAL_SHA: &str = "988cb00c22c80df26bb4c3a5281f8ab5e36cf00c006798a3593b41149457b794";

    #[test]
    fn equal_versions_are_current() {
        assert_eq!(compare_versions("0.2.16", bare("0.2.16")), UpdateState::Current);
    }

    #[test]
    fn newer_patch_minor_and_major_all_offer_an_update() {
        for (cur, new) in [
            ("0.2.16", "0.2.17"),
            ("0.2.16", "0.3.0"),
            ("0.2.16", "1.0.0"),
            ("0.2.9", "0.2.10"), // NOT a string comparison: "9" > "1" lexically
        ] {
            assert_eq!(compare_versions(cur, bare(new)), available(new), "{cur} -> {new}");
        }
    }

    #[test]
    fn a_local_build_ahead_of_published_is_not_called_latest() {
        assert_eq!(compare_versions("0.2.17", bare("0.2.16")), UpdateState::Ahead);
    }

    #[test]
    fn missing_segments_are_zero_padded_not_rejected() {
        assert_eq!(compare_versions("0.2", bare("0.2.0")), UpdateState::Current);
        assert_eq!(compare_versions("0.2", bare("0.2.1")), available("0.2.1"));
    }

    #[test]
    fn a_leading_v_is_tolerated_on_either_side() {
        assert_eq!(compare_versions("v0.2.16", bare("0.2.16")), UpdateState::Current);
        assert_eq!(compare_versions("0.2.16", bare("v0.2.16")), UpdateState::Current);
    }

    #[test]
    fn unparseable_input_yields_unknown_never_a_guess() {
        for (cur, latest) in [
            ("", "0.2.16"),
            ("0.2.16", ""),
            ("not-a-version", "0.2.16"),
            ("0.2.16", "0.2.x"),
            ("0.2..16", "0.2.16"),   // empty segment
            ("0.2.16", "1.2.3.4.5"), // too many segments
        ] {
            assert_eq!(compare_versions(cur, bare(latest)), UpdateState::Unknown, "{cur:?} vs {latest:?}");
        }
    }

    /// The AppImage reference rides through the comparison unchanged, into
    /// the `Available` variant.
    #[test]
    fn an_appimage_ref_survives_the_comparison_into_available() {
        let r = AppImageRef {
            filename: "axenstax-engine_0.2.18_x86_64.AppImage".to_string(),
            url: "https://docs.axenstax.org/download/installer/axenstax-engine_0.2.18_x86_64.AppImage"
                .to_string(),
            sha256: REAL_SHA.to_string(),
            mirrors: Vec::new(),
        };
        let latest = Latest { version: "0.2.18".to_string(), appimage: Some(r.clone()) };
        assert_eq!(
            compare_versions("0.2.16", latest),
            UpdateState::Available { version: "0.2.18".to_string(), appimage: Some(r) }
        );
    }

    /// The current 6-key `latest.json` document (design doc sample, also
    /// pinned server-side by `test_versioning.py`). If the server renames a
    /// key this is the test that goes red; nothing else ties the two halves
    /// together.
    #[test]
    fn the_docs_site_document_shape_parses_version_and_appimage_ref() {
        let body = format!(
            r#"{{"version":"0.2.18","linux_appimage":"axenstax-engine_0.2.18_x86_64.AppImage","android_apk":null,"download_url":"https://docs.axenstax.org/download","linux_appimage_sha256":"{REAL_SHA}","linux_appimage_url":"https://docs.axenstax.org/download/installer/axenstax-engine_0.2.18_x86_64.AppImage"}}"#
        );
        let latest = parse_latest(&body).expect("parses");
        assert_eq!(latest.version, "0.2.18");
        let r = latest.appimage.expect("appimage ref present");
        assert_eq!(r.filename, "axenstax-engine_0.2.18_x86_64.AppImage");
        assert_eq!(r.sha256, REAL_SHA);
        assert_eq!(
            r.url,
            "https://docs.axenstax.org/download/installer/axenstax-engine_0.2.18_x86_64.AppImage"
        );
    }

    /// An older 4-key manifest (pre-2026-09-03, before the sha256/url fields
    /// existed) still parses the version — it just carries no AppImage ref,
    /// so `self_update` is never offered against it.
    #[test]
    fn an_older_four_key_manifest_parses_version_with_no_appimage_ref() {
        let body = r#"{"version":"0.2.18","linux_appimage":"axenstax-engine_0.2.18_x86_64.AppImage","android_apk":null,"download_url":"https://docs.axenstax.org/download"}"#;
        let latest = parse_latest(body).expect("parses");
        assert_eq!(latest.version, "0.2.18");
        assert_eq!(latest.appimage, None);
    }

    /// No Linux build published yet: the site emits all three AppImage
    /// fields as `null`. Must not panic and must yield no AppImage ref.
    #[test]
    fn null_appimage_fields_yield_no_appimage_ref() {
        let body = format!(
            r#"{{"version":"0.2.18","linux_appimage":null,"android_apk":null,"download_url":"https://docs.axenstax.org/download","linux_appimage_sha256":null,"linux_appimage_url":null}}"#
        );
        let latest = parse_latest(&body).expect("parses");
        assert_eq!(latest.appimage, None);
    }

    /// A malformed sha256 (wrong length, or non-hex) must never be handed to
    /// `self_update`, which trusts it completely — this is the one place
    /// that guards it.
    #[test]
    fn a_malformed_sha256_yields_no_appimage_ref() {
        for bad_sha in [
            "988cb00c22c80df26bb4c3a5281f8ab5e36cf00c006798a3593b41149457b7", // 62 chars, too short
            "988cb00c22c80df26bb4c3a5281f8ab5e36cf00c006798a3593b41149457b7zz", // 64 chars but non-hex
            "",
        ] {
            let body = format!(
                r#"{{"version":"0.2.18","linux_appimage":"a.AppImage","android_apk":null,"download_url":"d","linux_appimage_sha256":"{bad_sha}","linux_appimage_url":"https://docs.axenstax.org/download/installer/a.AppImage"}}"#
            );
            let latest = parse_latest(&body).expect("parses");
            assert_eq!(latest.appimage, None, "sha {bad_sha:?}");
        }
    }

    /// An uppercase-hex sha256 in the manifest is tolerated and lowercased —
    /// `self_update` compares hex case-insensitively anyway, but normalising
    /// here keeps the stored value predictable.
    #[test]
    fn an_uppercase_sha256_is_lowercased() {
        let body = format!(
            r#"{{"version":"0.2.18","linux_appimage":"a.AppImage","android_apk":null,"download_url":"d","linux_appimage_sha256":"{}","linux_appimage_url":"https://docs.axenstax.org/download/installer/a.AppImage"}}"#,
            REAL_SHA.to_uppercase()
        );
        let latest = parse_latest(&body).expect("parses");
        assert_eq!(latest.appimage.unwrap().sha256, REAL_SHA);
    }

    /// Before any installer is published the site emits `"version": null`.
    /// That must collapse to Unknown, not a panic and not a bogus comparison.
    #[test]
    fn a_null_or_missing_version_is_unknown() {
        for body in [
            r#"{"version":null,"linux_appimage":null,"android_apk":null}"#,
            r#"{"linux_appimage":"x.AppImage"}"#,
            r#"{"version":""}"#,
            r#"{"version":42}"#,
            "not json",
            "",
        ] {
            assert_eq!(parse_latest(body), None, "{body:?}");
        }
    }

    #[test]
    fn this_binarys_own_version_parses() {
        // Guards against a Cargo.toml version that this module cannot read —
        // which would silently make the indicator Unknown forever.
        assert!(
            parse_version(current_version()).is_some(),
            "CARGO_PKG_VERSION {:?} is not parseable",
            current_version()
        );
    }

    fn signed(v: &str, url: &str) -> Latest {
        Latest {
            version: v.to_string(),
            appimage: Some(AppImageRef {
                filename: "axenstax-engine_0.3.0_x86_64.AppImage".to_string(),
                url: url.to_string(),
                sha256: REAL_SHA.to_string(),
                mirrors: Vec::new(),
            }),
        }
    }

    fn http_with_ref(v: &str, url: &str, sha: &str) -> Latest {
        Latest {
            version: v.to_string(),
            appimage: Some(AppImageRef {
                filename: "axenstax-engine_99.0.0_x86_64.AppImage".to_string(),
                url: url.to_string(),
                sha256: sha.to_string(),
                mirrors: Vec::new(),
            }),
        }
    }

    const EVIL_SHA: &str = "0000000000000000000000000000000000000000000000000000000000000000";

    /// The audit scenario: a compromised docs host publishes a higher version
    /// with its own URL + sha. With no signed event it may only NOTIFY.
    #[test]
    fn an_unsigned_http_manifest_can_never_supply_an_install_ref() {
        let http = http_with_ref("99.0.0", "https://evil.example/x.AppImage", EVIL_SHA);
        assert_eq!(decide("0.2.26", Some(http), None), available("99.0.0"));
    }

    /// With a signed event present, the HTTP version is ignored and the HTTP
    /// sha is never used — its URL only rides along as a mirror, held to the
    /// signed hash by `self_update`.
    #[test]
    fn the_signed_event_is_the_only_authority_for_version_url_and_sha() {
        let http = http_with_ref("99.0.0", "https://docs.example/mirror.AppImage", EVIL_SHA);
        let got = decide("0.2.26", Some(http), Some(signed("0.3.0", "https://signed.example/a.AppImage")));
        let UpdateState::Available { version, appimage: Some(r) } = got else {
            panic!("expected an installable update, got {got:?}");
        };
        assert_eq!(version, "0.3.0");
        assert_eq!(r.url, "https://signed.example/a.AppImage");
        assert_eq!(r.sha256, REAL_SHA, "the HTTP sha must never replace the signed one");
        assert_eq!(r.mirrors, vec!["https://docs.example/mirror.AppImage".to_string()]);
    }

    #[test]
    fn a_higher_unsigned_version_does_not_override_a_current_signed_one() {
        let http = http_with_ref("99.0.0", "https://evil.example/x.AppImage", EVIL_SHA);
        assert_eq!(
            decide("0.3.0", Some(http), Some(signed("0.3.0", "https://signed.example/a.AppImage"))),
            UpdateState::Current
        );
    }

    #[test]
    fn no_source_is_unknown_never_current() {
        assert_eq!(decide("0.2.26", None, None), UpdateState::Unknown);
    }

    #[test]
    fn appimage_filenames_must_be_safe_basenames() {
        assert!(is_valid_appimage_filename("axenstax-engine_0.2.26_x86_64.AppImage"));
        for bad in [
            "/../../x.AppImage",
            "../x.AppImage",
            "a/b.AppImage",
            "a\\b.AppImage",
            "x.AppImage.sh",
            ".AppImage",
            "",
            "x y.AppImage",
        ] {
            assert!(!is_valid_appimage_filename(bad), "{bad:?} must be rejected");
        }
    }

    #[test]
    fn an_http_manifest_with_a_traversal_filename_yields_no_ref() {
        let body = format!(
            r#"{{"version":"0.2.18","linux_appimage":"/../../x","linux_appimage_sha256":"{REAL_SHA}","linux_appimage_url":"https://e.example/x"}}"#
        );
        assert_eq!(parse_latest(&body).unwrap().appimage, None);
    }

    #[test]
    fn a_non_https_mirror_from_the_unsigned_manifest_is_dropped() {
        let http = http_with_ref("0.3.0", "http://192.168.1.1/x.AppImage", EVIL_SHA);
        let got = decide("0.2.26", Some(http), Some(signed("0.3.0", "https://signed.example/a.AppImage")));
        let UpdateState::Available { appimage: Some(r), .. } = got else { panic!("{got:?}") };
        assert!(r.mirrors.is_empty());
    }
}
